create table clientes (
    id integer generated by default as identity,
    nome_cliente varchar(255) not null,
    cpf varchar(11) not null,
    telefone varchar(20) not null,
    email varchar(100) not null,
    dt_nascimento date not null,
    primary key (id)
)