create table imoveis (
    id integer generated by default as identity,
    tipo_imovel varchar(50) not null,
    endereco varchar(255) not null,
    cep varchar(10) not null,
    dormitorios integer not null,
    banheiros integer not null,
    suites integer not null,
    metragem integer not null,
    valor_aluguel_sug decimal(10,2) not null,
    obs text,
    primary key (id)
)