create table locacao (
    id integer generated by default as identity,
    id_imovel integer not null,
    id_inquilino integer not null,
    ativo boolean not null default true,
    data_inicio date not null,
    data_fim date not null,
    dia_vencimento integer not null,
    perc_multa decimal(5,2) not null,
    valor_aluguel decimal(10,2) not null,
    obs text,
    primary key (id),
    constraint fk_locacao_imovel foreign key (id_imovel) references imoveis (id),
    constraint fk_locacao_inquilino foreign key (id_inquilino) references clientes (id)
)