create table alugueis (
    id integer generated by default as identity,
    id_locacao integer not null,
    dt_vencimento date not null,
    valor_pago decimal(10,2) not null,
    obs text,
    primary key (id),
    constraint fk_aluguel_locacao foreign key (id_locacao) references locacao (id)
)